---

apiVersion: v1
kind: Namespace
metadata:
  name: klum

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: klum
  namespace: klum
spec:
  replicas: 1
  selector:
    matchLabels:
      run: klum
  template:
    metadata:
      labels:
        run: klum
    spec:
      serviceAccountName: klum
      containers:
        - image: ghcr.io/jadolg/klum:v0.8.9
          imagePullPolicy: IfNotPresent
          name: klum
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsUser: 1000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: CONTEXT_NAME
              value: mycluster
            - name: SERVER_NAME
              value: https://myserver.example.com:6443
            - name: NAMESPACE
              value: klum

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: klum
  namespace: klum

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: klum-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: klum
    namespace: klum
